### ISSUE TITLE
Why a need for an external options.json file?

### ISSUE THREAD

**Issue by patrickbolle** [aqazix/printElements#10]
Hi there. Great looking plugin, but confused as to why you are referencing an external options.json file. Why not simply allow for an options object in library initialization?

Would simplify things immensely. This is the only plugin I've seen that doesn't provide an example of inline settings.

**Comment by aqazix** [comment]
Hello.
Thank you. This is one of our first projects and the first that we made available to public.
Honestly, it didn't occur to us. We'll be implementing this shortly.
